import type { Artwork } from '../types'

export const artistInfo = {
  name: 'Alemão Vargas Moreira',
  bio: 'Pintor realista com mais de 40 anos de ofício. Suas obras capturam a luz e a textura do cotidiano com uma precisão que transforma o comum em eterno. Acompanhe o processo de criação no TikTok.',
  tiktok: 'https://www.tiktok.com/@alemaovargasmoreira',
  tiktokHandle: '@alemaovargasmoreira',
  location: 'Brasil',
  speciality: 'Pintura a óleo realista',
}

export const mockArtworks: Artwork[] = [
  {
    _id: '1',
    title: 'Velha com Rosário',
    artist: 'Alemão Vargas Moreira',
    description: 'Retrato de uma senhora idosa em momento de devoção. A luz lateral revela cada detalhe do rosto, das mãos e do rosário desgastado pelo tempo.',
    price: 8500,
    year: 2023,
    dimensions: '60 × 80 cm',
    medium: 'Óleo sobre tela',
    category: 'Retrato',
    inStock: true,
    slug: { current: 'velha-com-rosario' },
    image: { asset: { _ref: '' }, alt: 'Velha com Rosário' },
  },
  {
    _id: '2',
    title: 'Mercado ao Entardecer',
    artist: 'Alemão Vargas Moreira',
    description: 'Cena de mercado popular no fim do dia. Frutas, vegetais e rostos cansados compõem uma narrativa visual rica em detalhes e humanidade.',
    price: 12000,
    year: 2024,
    dimensions: '100 × 70 cm',
    medium: 'Óleo sobre tela',
    category: 'Cena Urbana',
    inStock: true,
    slug: { current: 'mercado-ao-entardecer' },
    image: { asset: { _ref: '' }, alt: 'Mercado ao Entardecer' },
  },
  {
    _id: '3',
    title: 'Natureza Morta com Peixe',
    artist: 'Alemão Vargas Moreira',
    description: 'Composição clássica em tradição holandesa. A textura úmida do peixe, o reflexo nos utensílios de cobre e o pão rústico são tratados com maestria.',
    price: 6800,
    year: 2022,
    dimensions: '50 × 40 cm',
    medium: 'Óleo sobre tela',
    category: 'Natureza Morta',
    inStock: true,
    slug: { current: 'natureza-morta-com-peixe' },
    image: { asset: { _ref: '' }, alt: 'Natureza Morta com Peixe' },
  },
  {
    _id: '4',
    title: 'O Ferreiro',
    artist: 'Alemão Vargas Moreira',
    description: 'Retrato de um ferreiro em seu trabalho. O brilho do metal incandescente ilumina o rosto concentrado em uma cena de força e tradição.',
    price: 15000,
    year: 2023,
    dimensions: '80 × 100 cm',
    medium: 'Óleo sobre tela',
    category: 'Retrato',
    inStock: false,
    slug: { current: 'o-ferreiro' },
    image: { asset: { _ref: '' }, alt: 'O Ferreiro' },
  },
  {
    _id: '5',
    title: 'Rio São Francisco',
    artist: 'Alemão Vargas Moreira',
    description: 'Paisagem do São Francisco ao amanhecer. A névoa sobre as águas, as canoas e a vegetação da margem compõem um quadro de beleza serena.',
    price: 9200,
    year: 2024,
    dimensions: '120 × 60 cm',
    medium: 'Óleo sobre tela',
    category: 'Paisagem',
    inStock: true,
    slug: { current: 'rio-sao-francisco' },
    image: { asset: { _ref: '' }, alt: 'Rio São Francisco' },
  },
  {
    _id: '6',
    title: 'Menino com Papagaio',
    artist: 'Alemão Vargas Moreira',
    description: 'Retrato de criança com papagaio em luz de janela. Ternura e vivacidade captadas com técnica refinada.',
    price: 7400,
    year: 2022,
    dimensions: '55 × 70 cm',
    medium: 'Óleo sobre tela',
    category: 'Retrato',
    inStock: true,
    slug: { current: 'menino-com-papagaio' },
    image: { asset: { _ref: '' }, alt: 'Menino com Papagaio' },
  },
]

export const placeholderImages: Record<string, string> = {
  '1': 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&auto=format&fit=crop&q=80',
  '2': 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&auto=format&fit=crop&q=80',
  '3': 'https://images.unsplash.com/photo-1615184697985-c9bde1b07da7?w=800&auto=format&fit=crop&q=80',
  '4': 'https://images.unsplash.com/photo-1481961342978-73f92c2cbebb?w=800&auto=format&fit=crop&q=80',
  '5': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
  '6': 'https://images.unsplash.com/photo-1533827432537-70133748f5c8?w=800&auto=format&fit=crop&q=80',
}
